import pytest
from pydantic import ValidationError

from app.models import Record
from app.schemas.Record import RecordResponse
from conftest import AllowedRecordStatuses
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId


class TestResponseRecord:
    data_for_id = DataForId()
    status = AllowedRecordStatuses()

    @pytest.mark.parametrize("record, id, master_id, service_id, user_id, cell_id, status", [
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Created),
        (RecordResponse(id=data_for_id.big_right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         data_for_id.big_right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Created),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.big_right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         data_for_id.right_id, data_for_id.big_right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Created),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.big_right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         data_for_id.right_id, data_for_id.right_id, data_for_id.big_right_id, data_for_id.right_id,
         data_for_id.right_id, status.Created),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.big_right_id, cell_id=data_for_id.right_id, status=status.Created),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.big_right_id,
         data_for_id.right_id, status.Created),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.big_right_id, status=status.Created),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.big_right_id, status.Created),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Confirmed),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Confirmed),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Rejected),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Rejected),
        (RecordResponse(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Cancelled),
         data_for_id.right_id, data_for_id.right_id, data_for_id.right_id, data_for_id.right_id,
         data_for_id.right_id, status.Cancelled),
    ])
    def test_response_record_right(self, record, id, master_id, service_id, user_id, cell_id, status):
        record = RecordResponse.model_validate(record)
        assert isinstance(record, RecordResponse)
        assert record.id == id
        assert record.master_id == master_id
        assert record.service_id == service_id
        assert record.user_id == user_id
        assert record.cell_id == cell_id
        assert record.status == status

    @pytest.mark.parametrize("record, error_loc, error_type, error_msg", [
        (Record(id=data_for_id.wrong_id_zero, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.wrong_negative_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.big_wrong_negative_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.wrong_id_str, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_none, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_float, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_true, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_false, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
        user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_zero, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_negative_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.big_wrong_negative_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_str, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_none, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_float, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_true, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.wrong_id_false, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_zero,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_negative_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.big_wrong_negative_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_str,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_none,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_float,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_true,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.wrong_id_false,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.Created),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_zero, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_negative_id, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.big_wrong_negative_id, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_str, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_none, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_float, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_true, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.wrong_id_false, cell_id=data_for_id.right_id, status=status.Created),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_zero, status=status.Created),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_negative_id, status=status.Created),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.big_wrong_negative_id, status=status.Created),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_str, status=status.Created),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_none, status=status.Created),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_float, status=status.Created),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_true, status=status.Created),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.wrong_id_false, status=status.Created),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_string),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_none),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_empty),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_boolean),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_integer),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.right_id, master_id=data_for_id.right_id, service_id=data_for_id.right_id,
                user_id=data_for_id.right_id, cell_id=data_for_id.right_id, status=status.wrong_status_float),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
    ])
    def test_response_record_wrong(self, record, error_loc, error_type, error_msg):
        with pytest.raises(ValidationError) as error:
            record = RecordResponse.model_validate(record)
        errors = error.value.errors()
        assert len(errors) == 1
        error = errors[0]
        assert error["loc"] == error_loc
        assert error["type"] == error_type
        assert error_msg in error["msg"]
