import pytest
from pydantic import ValidationError

from app.models import Record
from app.schemas.Record import RecordUpdate
from tests.unit.test_schemas.conftest import assert_single_validation_error
from tests.unit.test_schemas.test_record.conftest import AllowedRecordStatuses
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId

data_for_id = DataForId()
status = AllowedRecordStatuses()


class TestUpdateRecord:

    @pytest.mark.parametrize("record, master_id, service_id, user_id, cell_id, status", [
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.big_correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created),
         data_for_id.big_correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.big_correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created),
         data_for_id.correct_id, data_for_id.big_correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.big_correct_id, cell_id=data_for_id.correct_id, status=status.Created),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.big_correct_id,
         data_for_id.correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.big_correct_id, status=status.Created),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.big_correct_id, status.Created),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Confirmed),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Confirmed),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Completed),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Completed),
        (RecordUpdate(master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Cancelled),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Cancelled),
        (RecordUpdate(master_id=data_for_id.correct_id),
         data_for_id.correct_id, None, None, None, None),
        (RecordUpdate(service_id=data_for_id.correct_id,),
         None, data_for_id.correct_id, None, None, None),
        (RecordUpdate(user_id=data_for_id.correct_id,),
         None, None, data_for_id.correct_id, None, None),
        (RecordUpdate(cell_id=data_for_id.correct_id,),
         None, None, None, data_for_id.correct_id, None),
        (RecordUpdate(status=status.Created),
         None, None, None, None, status.Created),
    ])
    def test_update_record_correct(self, record, master_id, service_id, user_id, cell_id, status):
        record = RecordUpdate.model_validate(record)
        assert isinstance(record, RecordUpdate)
        assert record.master_id == master_id
        assert record.service_id == service_id
        assert record.user_id == user_id
        assert record.cell_id == cell_id
        assert record.status == status

    @pytest.mark.parametrize("master_id, service_id, user_id, cell_id, status, error_loc, error_type, error_msg", [
        (data_for_id.wrong_id_zero, data_for_id.correct_id, data_for_id.correct_id,
        data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.wrong_negative_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.big_wrong_negative_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.wrong_id_str, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.wrong_id_float, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.wrong_id_true, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.wrong_id_false, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.wrong_id_zero, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.wrong_negative_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.big_wrong_negative_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.wrong_id_str, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.wrong_id_float, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.wrong_id_true, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.wrong_id_false, data_for_id.correct_id,
         data_for_id.correct_id, status.Created,
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_id_zero,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_negative_id,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.big_wrong_negative_id,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_id_str,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_id_float,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_id_true,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.wrong_id_false,
         data_for_id.correct_id, status.Created,
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_id_zero, status.Created,
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_negative_id, status.Created,
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.big_wrong_negative_id, status.Created,
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_id_str, status.Created,
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_id_float, status.Created,
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_id_true, status.Created,
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.wrong_id_false, status.Created,
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.wrong_status_string,
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.wrong_status_boolean,
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.wrong_status_empty,
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.wrong_status_integer,
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.wrong_status_float,
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
    ])
    def test_update_record_wrong(self, master_id, service_id, user_id, cell_id, status, error_loc, error_type, error_msg):
        with pytest.raises(ValidationError) as exc_info:
            RecordUpdate(
                master_id=master_id,
                service_id=service_id,
                user_id=user_id,
                cell_id=cell_id,
                status=status,
            )
        assert_single_validation_error(exc_info.value.errors(), error_loc, error_type, error_msg)
