from datetime import date, time

import pytest
from pydantic import ValidationError

from app.models import Record, Master, Service, Cell
from app.schemas.Record import FullRecordResponse
from conftest import AllowedRecordStatuses
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId


class TestFullResponseRecord:
    data_for_id = DataForId()
    status = AllowedRecordStatuses()
    master = Master(
        id = 1,
        specialization_id = 1,
        name = "Petr",
        phone = "+79990009090",
        email = "test@gmail.com",
        status = "ACTIVE"
    )
    service = Service(
        id = 1,
        name = "Haircut",
        price = 499.99,
        duration_minutes = 55,
        description = "Good haircut",
        category_id = 1,
    )
    cell = Cell(
        id = 1,
        master_id = 1,
        date = date.today(),
        time = time(hour=10, minute=0, second=0),
        status = "FREE"
    )

    @pytest.mark.parametrize("record, record_id, master_id, service_id, user_id, cell_id, status", [
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (Record(id=data_for_id.big_correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.big_correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.big_correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.big_correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.big_correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.big_correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Created),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.big_correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.big_correct_id,
         data_for_id.correct_id, status.Created),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.big_correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.big_correct_id, status.Created),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Confirmed,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Confirmed),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Completed,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Completed),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Cancelled,
        master=master, service=service, cell=cell),
         data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id, data_for_id.correct_id,
         data_for_id.correct_id, status.Cancelled),
    ])
    def test_full_response_record_correct(self, record, record_id, master_id, service_id, user_id, cell_id, status):
        record = FullRecordResponse.model_validate(record)
        assert isinstance(record, FullRecordResponse)
        assert record.id == record_id
        assert record.master_id == master_id
        assert record.service_id == service_id
        assert record.user_id == user_id
        assert record.cell_id == cell_id
        assert record.status == status
        assert record.master.id == 1
        assert record.service.id == 1
        assert record.cell.id == 1

    @pytest.mark.parametrize("record, error_loc, error_type, error_msg", [
        (Record(id=data_for_id.wrong_id_zero, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.wrong_negative_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.big_wrong_negative_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.wrong_id_str, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_none, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_float, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_true, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.wrong_id_false, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
        user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_zero, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_negative_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.big_wrong_negative_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_str, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_none, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_float, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_true, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.wrong_id_false, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("master_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_zero,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_negative_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.big_wrong_negative_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_str,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_none,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_float,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_true,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.wrong_id_false,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("service_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_zero, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_negative_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.big_wrong_negative_id, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_str, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_none, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_float, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_true, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.wrong_id_false, cell_id=data_for_id.correct_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("user_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_zero, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_negative_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.big_wrong_negative_id, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_str, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_none, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_float, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_true, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.wrong_id_false, status=status.Created,
        master=master, service=service, cell=cell),
         ("cell_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_string,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_none,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_empty,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_boolean,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_integer,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
        (Record(id=data_for_id.correct_id, master_id=data_for_id.correct_id, service_id=data_for_id.correct_id,
                user_id=data_for_id.correct_id, cell_id=data_for_id.correct_id, status=status.wrong_status_float,
        master=master, service=service, cell=cell),
         ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_RECORD),
    ])
    def test_response_record_wrong(self, record, error_loc, error_type, error_msg):
        with pytest.raises(ValidationError) as error:
            record = FullRecordResponse.model_validate(record)
        errors = error.value.errors()
        assert len(errors) == 1
        error = errors[0]
        assert error["loc"] == error_loc
        assert error["type"] == error_type
        assert error_msg in error["msg"]
