import phonenumbers
import pytest
from pydantic import ValidationError

from app.models import Master
from app.schemas.Master import MasterResponse
from tests.unit.test_schemas.conftest import assert_single_validation_error
from tests.unit.test_schemas.test_master.conftest import Name, Phone, Email, Status
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId

name = Name()
phone = Phone()
email = Email()
status = Status()
data_for_id = DataForId()


class TestResponseMaster:

    @pytest.mark.parametrize("master_data, master_id, specialization_id, name, phone, email, status", [
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name_short, 
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail, 
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name_short, phone.correct_number_str_with_eight, 
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name_long,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name_long, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name_cyrillic,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name_cyrillic, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_seven, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_seven,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_int, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_int,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_gmail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_gmail, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_yandex,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_yandex, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_long,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_long, status.correct_active),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_vacation),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_vacation),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_dismissed),
         data_for_id.correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_dismissed),
        (Master(id=data_for_id.correct_id, specialization_id=data_for_id.big_correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.correct_id, data_for_id.big_correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_active),
        (Master(id=data_for_id.big_correct_id, specialization_id=data_for_id.correct_id, name=name.correct_name,
                        phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
                        status=status.correct_active),
         data_for_id.big_correct_id, data_for_id.correct_id, name.correct_name, phone.correct_number_str_with_eight,
         email.correct_string_mail, status.correct_active),
    ])
    def test_response_master_correct(self, master_data, master_id, specialization_id, name, phone, email, status):
        master = MasterResponse.model_validate(master_data)
        assert isinstance(master, MasterResponse)
        assert master.specialization_id == specialization_id
        assert master.name == name.title()
        parsed = phonenumbers.parse(str(phone), "RU")
        if phonenumbers.is_valid_number(parsed):
            assert master.phone == phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)
        assert master.email == email
        assert master.status == status

    @pytest.mark.parametrize(
        "master_data, error_loc, error_type, error_msg", [
            (Master(name=name.wrong_name_long, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TOO_LONG, ErrorMessages.STRING_TOO_LONG_30),
            (Master(name=name.wrong_name_short, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_int, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.wrong_name_empty, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_spaces, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_none, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.wrong_invalid_character, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_INVALID_CHARACTER),
            (Master(name=name.wrong_consecutive_spaces, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_SPACES),
            (Master(name=name.wrong_consecutive_hyphens, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_HYPHENS),
            (Master(name=name.wrong_consecutive_apostrophes, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_APOSTROPHES),
            (Master(name=name.wrong_consecutive_underscores, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_UNDERSCORES),
            (Master(name=name.wrong_start_with_hyphen, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_HYPHEN),
            (Master(name=name.wrong_start_with_apostrophe, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_APOSTROPHE),
            (Master(name=name.wrong_start_with_underscore, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_UNDERSCORE),
            (Master(name=name.wrong_end_with_hyphen, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_HYPHEN),
            (Master(name=name.wrong_end_with_apostrophe, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_APOSTROPHE),
            (Master(name=name.wrong_end_with_underscore, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_UNDERSCORE),
            (Master(name=name.wrong_space_and_hyphen_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (Master(name=name.wrong_space_and_apostrophe_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (Master(name=name.wrong_space_and_underscore_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (Master(name=name.wrong_hyphen_and_space_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (Master(name=name.wrong_apostrophe_and_space_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (Master(name=name.wrong_underscore_and_space_adjacent, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_two_without_plus, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_five_without_plus, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_two_with_plus, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_five_with_plus, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_eight_with_plus, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_seven_short, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_int_short, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_str_with_seven_long, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_int_long, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_none, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.correct_name, phone=phone.wrong_number_empty, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.correct_name, phone=phone.wrong_number_true, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.correct_name, phone=phone.wrong_number_false, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_without_dog,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_without_email,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_PERIOD),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_mail_without_dot,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_mail_without_ru,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_END_WITH_PERIOD),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_without_dog_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_string_without_dot_ru,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_email_int,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_email_none,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_email_empty,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_email_true,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.wrong_email_false,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_string, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_none, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_empty, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_boolean, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_integer, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.wrong_status_float, specialization_id=data_for_id.correct_id, id=data_for_id.correct_id,),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_zero, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_negative_id, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_str, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_none, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_float, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_true, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.wrong_id_false, id=data_for_id.correct_id,),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_zero,),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_negative_id,),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_str,),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_none,),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_float,),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_true,),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.correct_name, phone=phone.correct_number_str_with_eight, email=email.correct_string_mail,
             status=status.correct_active, specialization_id=data_for_id.correct_id, id=data_for_id.wrong_id_false,),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        ]
    )
    def test_response_master_wrong(
            self,
            master_data,
            error_loc,
            error_type,
            error_msg
    ):
        with pytest.raises(ValidationError) as exc_info:
            MasterResponse.model_validate(master_data)
        assert_single_validation_error(exc_info.value.errors(), error_loc, error_type, error_msg)

