import phonenumbers
import pytest
from pydantic import ValidationError

from app.schemas.Master import MasterCreate
from conftest import Name, Phone, Email, Status
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId


class TestCreateMaster:
    name = Name()
    phone = Phone()
    email = Email()
    status = Status()
    data_for_id = DataForId()

    @pytest.mark.parametrize("specialization_id, name, phone, email, status", [
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name_short, phone.right_number_str_with_eight, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name_long, phone.right_number_str_with_eight, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name_сyrillic, phone.right_number_str_with_eight, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_seven, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_int, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_seven_without_plus, email.right_string_mail, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_gmail, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_yandex, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_long, status.right_active),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_mail, status.right_vacation),
        (data_for_id.right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_mail, status.right_dismissed),
        (data_for_id.big_right_id, name.right_name, phone.right_number_str_with_eight, email.right_string_mail, status.right_active),
    ])
    def test_create_master_right(self, specialization_id, name, phone, email, status):
        master = MasterCreate(
            specialization_id=specialization_id,
            name=name,
            phone=phone,
            email=email,
            status=status,
        )
        assert isinstance(master, MasterCreate)
        assert master.specialization_id == specialization_id
        assert master.name == name.title()
        parsed = phonenumbers.parse(str(phone), "RU")
        if phonenumbers.is_valid_number(parsed):
            assert master.phone == phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)
        assert master.email == email
        assert master.status == status

    @pytest.mark.parametrize(
        "name, phone, email, status, specialization_id, error_loc, error_type, error_msg", [
            (name.wrong_name_long, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TOO_LONG, ErrorMessages.STRING_TOO_LONG_30),
            (name.wrong_name_short, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (name.wrong_name_int, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.wrong_name_empty, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (name.wrong_name_spaces, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (name.wrong_name_none, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.wrong_invalid_character, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_INVALID_CHARACTER),
            (name.wrong_consecutive_spaces, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_SPACES),
            (name.wrong_consecutive_hyphens, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_HYPHENS),
            (name.wrong_consecutive_apostrophes, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_APOSTROPHES),
            (name.wrong_consecutive_underscores, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_UNDERSCORES),
            (name.wrong_start_with_hyphen, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_HYPHEN),
            (name.wrong_start_with_apostrophe, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_APOSTROPHE),
            (name.wrong_start_with_underscore, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_UNDERSCORE),
            (name.wrong_end_with_hyphen, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_HYPHEN),
            (name.wrong_end_with_apostrophe, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_APOSTROPHE),
            (name.wrong_end_with_underscore, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_UNDERSCORE),
            (name.wrong_space_and_hyphen_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (name.wrong_space_and_apostrophe_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (name.wrong_space_and_underscore_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (name.wrong_hyphen_and_space_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (name.wrong_apostrophe_and_space_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (name.wrong_underscore_and_space_adjacent, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (name.right_name, phone.wrong_number_str_with_two_without_plus, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_five_without_plus, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_two_with_plus, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_five_with_plus, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_eight_with_plus, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_seven_short, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_int_short, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_str_with_seven_long, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_int_long, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_none, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (name.right_name, phone.wrong_number_empty, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (name.right_name, phone.wrong_number_true, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (name.right_name, phone.wrong_number_false, email.right_string_mail,
             status.right_active, data_for_id.right_id,
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_without_dog,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_without_email,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_PERIOD),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_mail_without_dot,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_mail_without_ru,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_END_WITH_PERIOD),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_without_dog_mail,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_string_without_dot_ru,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_email_int,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_email_none,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_email_empty,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_email_true,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.wrong_email_false,
             status.right_active, data_for_id.right_id,
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_string, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_none, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_empty, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_boolean, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_integer, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.wrong_status_float, data_for_id.right_id,
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_zero,
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_negative_id,
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_negative_id,
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_str,
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_none,
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_float,
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_true,
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (name.right_name, phone.right_number_str_with_eight, email.right_string_mail,
             status.right_active, data_for_id.wrong_id_false,
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        ]
    )
    def test_create_master_wrong(self, name, phone, email, status, specialization_id, error_loc, error_type, error_msg):
        with pytest.raises(ValidationError) as error:
            master = MasterCreate(
                specialization_id=specialization_id,
                name=name,
                phone=phone,
                email=email,
                status=status,
            )
        errors = error.value.errors()
        assert len(errors) == 1
        error = errors[0]
        assert error["loc"] == error_loc
        assert error["type"] == error_type
        assert error_msg in error["msg"]

