import phonenumbers
import pytest
from pydantic import ValidationError

from app.models import Master, Specialization
from app.schemas.Master import MasterFullResponse
from app.schemas.Specialization import SpecializationResponse
from conftest import Name, Phone, Email, Status
from tests.unit.test_schemas.conftest_exceptions import ErrorMessages, ErrorTypes, DataForId


class TestFullResponseMaster:
    name = Name()
    phone = Phone()
    email = Email()
    status = Status()
    data_for_id = DataForId()
    specialization = SpecializationResponse(
        id=1,
        name="Barber",
    )
    specialization_orm = Specialization(
        id=1,
        name="Barber",
    )

    @pytest.mark.parametrize("master_data, master_id, specialization_id, name, phone, email, status", [
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name_short, 
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail, 
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name_short, phone.right_number_str_with_eight, 
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name_long,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name_long, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name_сyrillic,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name_сyrillic, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_seven, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_seven,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_int, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_int,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_gmail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_gmail, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_yandex,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_yandex, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_long,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_long, status.right_active),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_vacation, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_vacation),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_dismissed, specialization=specialization),
         data_for_id.right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_dismissed),
        (MasterFullResponse(id=data_for_id.right_id, specialization_id=data_for_id.big_right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.right_id, data_for_id.big_right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_active),
        (MasterFullResponse(id=data_for_id.big_right_id, specialization_id=data_for_id.right_id, name=name.right_name,
                        phone=phone.right_number_str_with_eight, email=email.right_string_mail,
                        status=status.right_active, specialization=specialization),
         data_for_id.big_right_id, data_for_id.right_id, name.right_name, phone.right_number_str_with_eight,
         email.right_string_mail, status.right_active),
    ])
    def test_full_response_master_right(self, master_data, master_id, specialization_id, name, phone, email, status):
        master = MasterFullResponse.model_validate(master_data)
        assert isinstance(master, MasterFullResponse)
        assert master.specialization_id == specialization_id
        assert master.name == name.title()
        parsed = phonenumbers.parse(str(phone), "RU")
        if phonenumbers.is_valid_number(parsed):
            assert master.phone == phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)
        assert master.email == email
        assert master.status == status
        assert master.specialization.id == 1
        assert master.specialization.name == "Barber"
    
    @pytest.mark.parametrize(
        "master, error_loc, error_type, error_msg", [
            (Master(name=name.wrong_name_long, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TOO_LONG, ErrorMessages.STRING_TOO_LONG_30),
            (Master(name=name.wrong_name_short, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_int, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.wrong_name_empty, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_spaces, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TOO_SHORT, ErrorMessages.STRING_TOO_SHORT),
            (Master(name=name.wrong_name_none, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.wrong_invalid_character, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_INVALID_CHARACTER),
            (Master(name=name.wrong_consecutive_spaces, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_SPACES),
            (Master(name=name.wrong_consecutive_hyphens, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_HYPHENS),
            (Master(name=name.wrong_consecutive_apostrophes, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_APOSTROPHES),
            (Master(name=name.wrong_consecutive_underscores, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_CONSECUTIVE_UNDERSCORES),
            (Master(name=name.wrong_start_with_hyphen, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_HYPHEN),
            (Master(name=name.wrong_start_with_apostrophe, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_APOSTROPHE),
            (Master(name=name.wrong_start_with_underscore, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_START_WITH_UNDERSCORE),
            (Master(name=name.wrong_end_with_hyphen, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_HYPHEN),
            (Master(name=name.wrong_end_with_apostrophe, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_APOSTROPHE),
            (Master(name=name.wrong_end_with_underscore, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_END_WITH_UNDERSCORE),
            (Master(name=name.wrong_space_and_hyphen_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (Master(name=name.wrong_space_and_apostrophe_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (Master(name=name.wrong_space_and_underscore_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (Master(name=name.wrong_hyphen_and_space_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_HYPHEN_ADJACENT),
            (Master(name=name.wrong_apostrophe_and_space_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_APOSTROPHE_ADJACENT),
            (Master(name=name.wrong_underscore_and_space_adjacent, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("name",), ErrorTypes.VALUE_ERROR, ErrorMessages.WRONG_SPACE_AND_UNDERSCORE_ADJACENT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_two_without_plus, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_five_without_plus, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_two_with_plus, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_five_with_plus, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_eight_with_plus, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_seven_short, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_int_short, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_str_with_seven_long, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_int_long, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_none, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.right_name, phone=phone.wrong_number_empty, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.right_name, phone=phone.wrong_number_true, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.INVALID_PHONE_FORMAT),
            (Master(name=name.right_name, phone=phone.wrong_number_false, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("phone",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMPTY_PHONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_without_dog,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_without_email,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_PERIOD),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_mail_without_dot,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_mail_without_ru,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_END_WITH_PERIOD),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_without_dog_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_string_without_dot_ru,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_INVALID_PERIOD),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_email_int,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_email_none,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_email_empty,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.VALUE_ERROR, ErrorMessages.EMAIL_MISS_DOG),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_email_true,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.wrong_email_false,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("email",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_string, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_none, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_empty, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_boolean, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_integer, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.wrong_status_float, specialization_id=data_for_id.right_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("status",), ErrorTypes.ENUM, ErrorMessages.ENUM_MASTER),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_zero, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_negative_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_negative_id, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_str, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_none, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_float, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_true, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.wrong_id_false, id=data_for_id.right_id,
             specialization=specialization_orm),
             ("specialization_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_zero,
             specialization=specialization_orm),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_negative_id,
             specialization=specialization_orm),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_negative_id,
             specialization=specialization_orm),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_str,
             specialization=specialization_orm),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_none,
             specialization=specialization_orm),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_float,
             specialization=specialization_orm),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_true,
             specialization=specialization_orm),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Master(name=name.right_name, phone=phone.right_number_str_with_eight, email=email.right_string_mail,
             status=status.right_active, specialization_id=data_for_id.right_id, id=data_for_id.wrong_id_false,
             specialization=specialization_orm),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
        ]
    )
    def test_full_response_wrong(
            self,
            master,
            error_loc,
            error_type,
            error_msg
    ):
        with pytest.raises(ValidationError) as error:
            master = MasterFullResponse.model_validate(master)
        errors = error.value.errors()
        assert len(errors) == 1
        error = errors[0]
        assert error["loc"] == error_loc
        assert error["type"] == error_type
        assert error_msg in error["msg"]
