"""Replace phone_number and email 

Revision ID: 163f56809e33
Revises: e5809bb1ba5a
Create Date: 2026-02-03 12:47:13.404329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.core.security import get_password_hash


# revision identifiers, used by Alembic.
revision: str = '163f56809e33'
down_revision: Union[str, Sequence[str], None] = 'e5809bb1ba5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('masters_email_key'), 'masters', type_='unique')
    op.drop_constraint(op.f('masters_phone_email_key'), 'masters', type_='unique')
    op.drop_column('masters', 'email')
    op.drop_column('masters', 'phone')
    op.add_column('workers', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('workers', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint("uq_workers_phone_email", "workers", ["phone", "email"])
    op.create_unique_constraint("uq_workers_email", "workers", ["email"])
    

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(
        sa.text("""
                INSERT INTO workers (id, master_id, username, phone, email, password, is_master, is_admin, is_active) 
                VALUES (:id, :master_id, :username, :phone, :email, :password, :is_master, :is_admin, :is_active)
            """),
        [
            {
                "id": 1,
                "master_id": None,
                "phone": "+79009009090",
                "email": "applelemon647@gmail.com",
                "username": "I_am_admin",
                "password": get_password_hash("Zxc-q123"),
                "is_master": False,
                "is_admin": True,
                "is_active": True
            },
        ]
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_workers_email", "workers", type_="unique")
    op.drop_constraint("uq_workers_phone_email", "workers", type_="unique")
    op.drop_column('workers', 'email')
    op.drop_column('workers', 'phone')
    # nullable=True: при откате в masters уже могут быть строки без phone/email (из тестов),
    # NOT NULL привёл бы к IntegrityError при teardown
    op.add_column('masters', sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('masters', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('masters_phone_email_key'), 'masters', ['phone', 'email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('masters_email_key'), 'masters', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
