"""Delete feedbacl

Revision ID: 3054e8eaa54d
Revises: f0f93fac6fa1
Create Date: 2026-01-25 16:57:19.510904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3054e8eaa54d'
down_revision: Union[str, Sequence[str], None] = 'f0f93fac6fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('master_estimation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('master_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salon_estimation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salon_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('feedbacks_record_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedbacks_pkey'))
    )
    # ### end Alembic commands ###
