"""Create Worker table

Revision ID: 61eff3917886
Revises: 6549b0fd1866
Create Date: 2026-01-12 18:13:32.835908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61eff3917886'
down_revision: Union[str, Sequence[str], None] = '6549b0fd1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'specialization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'specialization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
