"""Update uniq in naster

Revision ID: 62d4f4b9c7b8
Revises: 7ab1dbb8cc07
Create Date: 2026-01-05 15:41:03.332383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d4f4b9c7b8'
down_revision: Union[str, Sequence[str], None] = '7ab1dbb8cc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'masters', ['email'])
    op.create_unique_constraint(None, 'masters', ['phone', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masters', type_='unique')
    op.drop_constraint(None, 'masters', type_='unique')
    # ### end Alembic commands ###
