"""Update uniq fields

Revision ID: 6549b0fd1866
Revises: 62d4f4b9c7b8
Create Date: 2026-01-06 19:26:35.220320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6549b0fd1866'
down_revision: Union[str, Sequence[str], None] = '62d4f4b9c7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'services', ['name'])
    op.create_unique_constraint(None, 'specializations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specializations', type_='unique')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
