"""Master and service teble

Revision ID: 835ac28d3b90
Revises: f965e488970b
Create Date: 2025-12-23 15:02:18.361069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835ac28d3b90'
down_revision: Union[str, Sequence[str], None] = 'f965e488970b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('work_schedule', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('records', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('records', sa.Column('master_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'records', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'records', 'masters', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'master_id')
    op.drop_column('records', 'service_id')
    op.drop_table('services')
    op.drop_table('masters')
    # ### end Alembic commands ###
