"""Update record

Revision ID: c19e6765e024
Revises: f190a694a69c
Create Date: 2025-11-30 15:08:09.724527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19e6765e024'
down_revision: Union[str, Sequence[str], None] = 'f190a694a69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('records', sa.Column('time', sa.Time(), nullable=False))
    op.drop_index(op.f('ix_records_Date'), table_name='records')
    op.create_index(op.f('ix_records_date'), 'records', ['date'], unique=False)
    op.drop_column('records', 'Time')
    op.drop_column('records', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('Date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('records', sa.Column('Time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_records_date'), table_name='records')
    op.create_index(op.f('ix_records_Date'), 'records', ['Date'], unique=False)
    op.drop_column('records', 'time')
    op.drop_column('records', 'date')
    # ### end Alembic commands ###
