"""Make other tables

Revision ID: cd412ad69bdc
Revises: 835ac28d3b90
Create Date: 2025-12-24 19:25:42.512604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd412ad69bdc'
down_revision: Union[str, Sequence[str], None] = '835ac28d3b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'date', 'time', name='uq_master_datetime')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('monday_start', sa.Time(), nullable=True),
    sa.Column('monday_end', sa.Time(), nullable=True),
    sa.Column('tuesday_start', sa.Time(), nullable=True),
    sa.Column('tuesday_end', sa.Time(), nullable=True),
    sa.Column('wednesday_start', sa.Time(), nullable=True),
    sa.Column('wednesday_end', sa.Time(), nullable=True),
    sa.Column('thursday_start', sa.Time(), nullable=True),
    sa.Column('thursday_end', sa.Time(), nullable=True),
    sa.Column('friday_start', sa.Time(), nullable=True),
    sa.Column('friday_end', sa.Time(), nullable=True),
    sa.Column('saturday_start', sa.Time(), nullable=True),
    sa.Column('saturday_end', sa.Time(), nullable=True),
    sa.Column('sunday_start', sa.Time(), nullable=True),
    sa.Column('sunday_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id')
    )
    op.create_table('specialization_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialization_id', 'service_id', name='uq_specialization_service')
    )
    op.add_column('masters', sa.Column('specialization_id', sa.Integer(), nullable=True))
    op.create_foreign_key("masters_specializations", 'masters', 'specializations', ['specialization_id'], ['id'])
    op.drop_column('masters', 'specialization')
    op.drop_column('masters', 'work_schedule')
    op.add_column('records', sa.Column('cell_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_records_date'), table_name='records')
    op.create_foreign_key("records_cells", 'records', 'cells', ['cell_id'], ['id'])
    op.drop_column('records', 'time')
    op.drop_column('records', 'date')
    op.drop_column('records', 'price')
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.create_foreign_key("services_categories", 'services', 'categories', ['category_id'], ['id'])
    op.drop_column('services', 'duration')
    op.drop_column('services', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("services_categories", 'services', type_='foreignkey')
    op.alter_column('services', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('services', 'category_id')
    op.drop_column('services', 'duration_minutes')
    op.add_column('records', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('records', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('records', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint("records_cells", 'records', type_='foreignkey')
    op.create_index(op.f('ix_records_date'), 'records', ['date'], unique=False)
    op.drop_column('records', 'cell_id')
    op.add_column('masters', sa.Column('work_schedule', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('masters', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint("masters_specializations", 'masters', type_='foreignkey')
    op.drop_column('masters', 'specialization_id')
    op.drop_table('specialization_services')
    op.drop_table('schedules')
    op.drop_table('cells')
    op.drop_table('specializations')
    op.drop_table('categories')
    # ### end Alembic commands ###
