"""Init DB

Revision ID: e5809bb1ba5a
Revises: 
Create Date: 2026-01-25 18:31:31.136801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.core.security import get_password_hash

# revision identifiers, used by Alembic.
revision: str = 'e5809bb1ba5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('masters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'VACATION', 'DISMISSED', name='allowedmasterstatuses'), server_default='ACTIVE', nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone', 'email')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'OCCUPIED', name='allowedcellsstatuses'), server_default='FREE', nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'date', 'time', name='uq_master_datetime')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('monday_start', sa.Time(), nullable=True),
    sa.Column('monday_end', sa.Time(), nullable=True),
    sa.Column('tuesday_start', sa.Time(), nullable=True),
    sa.Column('tuesday_end', sa.Time(), nullable=True),
    sa.Column('wednesday_start', sa.Time(), nullable=True),
    sa.Column('wednesday_end', sa.Time(), nullable=True),
    sa.Column('thursday_start', sa.Time(), nullable=True),
    sa.Column('thursday_end', sa.Time(), nullable=True),
    sa.Column('friday_start', sa.Time(), nullable=True),
    sa.Column('friday_end', sa.Time(), nullable=True),
    sa.Column('saturday_start', sa.Time(), nullable=True),
    sa.Column('saturday_end', sa.Time(), nullable=True),
    sa.Column('sunday_start', sa.Time(), nullable=True),
    sa.Column('sunday_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id')
    )
    op.create_table('specialization_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialization_id', 'service_id', name='uq_specialization_service')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='allowedrecordstatuses'), server_default='CREATED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(
        sa.text("""
                INSERT INTO workers (id, master_id, username, password, is_master, is_admin, is_active) 
                VALUES (:id, :master_id, :username, :password, :is_master, :is_admin, :is_active)
            """),
        [
            {
                "id": "1",
                "master_id": None,
                "username": "I_am_admin",
                "password": get_password_hash("Zxc-q123"),
                "is_master": False,
                "is_admin": True,
                "is_active": True
            },
        ]
    )
    session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('workers')
    op.drop_table('specialization_services')
    op.drop_table('schedules')
    op.drop_table('cells')
    op.drop_table('services')
    op.drop_table('masters')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('specializations')
    op.drop_table('categories')
    # ### end Alembic commands ###
