"""Create feedback table

Revision ID: f0f93fac6fa1
Revises: bf1e6e1a5d82
Create Date: 2026-01-15 17:16:34.604038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f93fac6fa1'
down_revision: Union[str, Sequence[str], None] = 'bf1e6e1a5d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('master_estimation', sa.Integer(), nullable=False),
    sa.Column('master_comment', sa.Text(), nullable=True),
    sa.Column('salon_estimation', sa.Integer(), nullable=False),
    sa.Column('salon_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
