import pytest
from pydantic import ValidationError

from app.models import Feedback
from app.schemas.Feedback import SmallFeedbackResponse
from tests.unit.test_schemas.conftest_exceptions import DataForId, ErrorTypes, ErrorMessages
from conftest import Estimation, Comment


class TestSmallResponseFeedback:
    estimation = Estimation()
    comment = Comment()
    data_for_id = DataForId()

    @pytest.mark.parametrize(
        "feedback, feedback_id, record_id, master_estimation, master_comment, salon_estimation, salon_comment",
        [
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_two, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_two, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_two, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_two, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_three, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_three, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_three, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_three, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_four, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_four, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_four, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_four, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_five, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_five, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_five, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_five, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.big_right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.big_right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.big_right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.big_right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_long_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_long_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_long_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_long_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_none_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_none_comment,
                estimation.right_estimation_one, comment.right_short_comment,
            ),
            (
                Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                         master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                         salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_none_comment),
                data_for_id.right_id, data_for_id.right_id,
                estimation.right_estimation_one, comment.right_short_comment,
                estimation.right_estimation_one, comment.right_none_comment,
            ),
        ]
    )
    def test_right_create_feedback(
            self,
            feedback,
            feedback_id,
            record_id,
            master_estimation,
            master_comment,
            salon_estimation,
            salon_comment
    ):
        feedback = SmallFeedbackResponse(
            id=feedback_id,
            record_id=record_id,
            master_estimation=master_estimation,
            master_comment=master_comment,
            salon_estimation=salon_estimation,
            salon_comment=salon_comment,
        )
        assert feedback.id == feedback_id
        assert feedback.record_id == record_id
        assert feedback.master_estimation == master_estimation
        assert feedback.master_comment == master_comment
        assert feedback.salon_estimation == salon_estimation
        assert feedback.salon_comment == salon_comment


    @pytest.mark.parametrize(
        "feedback,error_loc,error_type,error_msg",
        [
            (Feedback(id=data_for_id.wrong_id_zero, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.wrong_negative_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.big_wrong_negative_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.wrong_id_str, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.wrong_id_float, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.wrong_id_true, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.wrong_id_false, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.wrong_id_none, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_zero,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_negative_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.big_wrong_negative_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_str,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_float,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_true,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_false,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.wrong_id_none,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("record_id",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_six, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.LESS_THAN_EQUAL, ErrorMessages.LESS_THAN_EQUAL_5),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_zero, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_negative_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_float, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_true, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_false, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_none, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.wrong_estimation_string, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_six, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.LESS_THAN_EQUAL, ErrorMessages.LESS_THAN_EQUAL_5),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_zero, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_negative_one, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.GREATER_THAN_EQUAL, ErrorMessages.ID_GREATER_ONE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_float, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_true, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_false, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_none, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.wrong_estimation_string, salon_comment=comment.right_short_comment),
             ("salon_estimation",), ErrorTypes.INT_TYPE, ErrorMessages.INT_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.wrong_float_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.wrong_bool_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.wrong_int_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.right_short_comment),
             ("master_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.wrong_float_comment),
             ("salon_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.wrong_bool_comment),
             ("salon_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
            (Feedback(id=data_for_id.right_id, record_id=data_for_id.right_id,
                      master_estimation=estimation.right_estimation_one, master_comment=comment.right_short_comment,
                      salon_estimation=estimation.right_estimation_one, salon_comment=comment.wrong_int_comment),
             ("salon_comment",), ErrorTypes.STRING_TYPE, ErrorMessages.STRING_TYPE),
        ]
    )
    def test_wrong_create_feedback(
            self,
            feedback,
            error_loc,
            error_type,
            error_msg
    ):
        with pytest.raises(ValidationError) as error:
            feedback = SmallFeedbackResponse.model_validate(feedback)
        errors = error.value.errors()
        assert len(errors) == 1
        error = errors[0]
        assert error["loc"] == error_loc
        assert error["type"] == error_type
        assert error_msg in error["msg"]
